# fly.toml app configuration file generated for travel-agency-humbolt-latam on 2024-12-29T01:39:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'travel-agency-humbolt-latam'
primary_region = 'scl'
console_command = '/rails/bin/rails console'

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[env]
  PORT = '8080'

[processes]
  app = './bin/rails server'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
